fixed Bold/italic formatting only works single letter/word (ios11)
LyokoTech/RichTextVC-iOS pull request #23
Opened 2017-10-17 15:56 UTC by ryanplitt

previousTypingAttributes need to be applied to the text before the text is changed (instead of after). This will allow it to continue the previous formatting.

2017-10-17 20:14 UTC, SerenadeX requested changes
Can you bump up the version in the `podspec` to `2.0.5`?

2017-10-17 20:58 UTC, SerenadeX approved these changes

2017-10-17 21:40 UTC, SerenadeX approved these changes

2017-10-26 22:40 UTC, samuelbradshaw commented
@SerenadeX, is this ready to merge? I'm hoping we can get this into GL 4.2.0.

2017-10-28 14:30 UTC, merged

2017-10-28 14:47 UTC, SerenadeX commented
Ok this is pushed up to the trunk of Cocoapods.  2.0.5 should be available now for GL

2017-10-30 15:57 UTC, samuelbradshaw commented
Thanks!