Compare fontName. Fix issue mentioned in GLI-3964
LyokoTech/RichTextVC-iOS pull request #25
Opened 2018-06-01 20:12 UTC by aaronmartinez6

Checking for the exact match of fonts never returned true. I noticed 
the font sizes were a little off when comparing the two. Let me know
if this isn't the correct fix and if I need to go address the font size 
difference instead.

2018-06-04 16:16 UTC, SerenadeX approved these changes

2018-06-04 16:16 UTC, SerenadeX requested changes
Can you update the version number in the `.podspec`?

2018-06-04 16:19 UTC, joshuadone approved these changes

2018-06-05 02:44 UTC, SerenadeX approved these changes

2018-06-07 16:33 UTC, merged